### ISSUE TITLE
Add contract events subscription functionality

### ISSUE THREAD

**Issue by fallafeljan** [JoinColony/colonyJS#117]
As a developer using the colonyJS library, I want to subscribe to contract events of the colonyNetwork contracts, so that I can process data in real time and integrate .

Suggestion: Add base functionality into the abstract `Adapter` interface as well as the Ethers adapter, then add methods to `ColonyClient`.

**Comment by chmanie** [comment]
Let's close #74 then

**Comment by JamesLefrere** [comment]
Done
