### ISSUE TITLE
Check documentation (given recent updates)

### ISSUE THREAD

**Issue by JamesLefrere** [JoinColony/colonyJS#128]
Given these PRs:

* https://github.com/JoinColony/colonyJS/pull/122
* https://github.com/JoinColony/colonyJS/pull/123
* https://github.com/JoinColony/colonyJS/pull/124

Ensure that the documentation that isn't automatically generated (e.g. Quickstart) is up-to-date.

**Comment by chmanie** [comment]
@JamesLefrere, could you check please? I think there shouldn't be much of a change there, but you'll know better
