### ISSUE TITLE
Doc fixes for "Get started"

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyJS#150]
- [ ] do not use `start:blockchain:client`
- [ ] Improve “how to use with colonyJS” section in colonyNetwork (also link to that section from colonyJs)
- [ ] Be consistent with the trufflepig docs
- [x] Merge with Quickstart (and remove quickstart)
- [x] Create a new token in the example. Like this maybe: https://gist.github.com/chmanie/85f1c5cdf5a9f29b47096d05dac32acf

This is the process which needs to be documented:

1. clone the colonyNetwork to a new location using the command: `git clone --recursive https://github.com/JoinColony/colonyNetwork.git`
2. Then in the `colonyNetwork` dir do git checkout `ce9811a9f0fca53d9ab417d5fc24bbcf29c351c8`
3. In `colonyNetwork` do `yarn`
4. Install `ganache-cli` and `trufflepig` globally
5. Run in `colonyNetwork`: `ganache-cli -d —gasLimit 7000000 —acctKeys ganache-accounts.json`
6. In `colonyNetwork` do: `node_modules/.bin/truffle migrate`
7. In the same dir do: `trufflepig —ganacheKeyFile ganache-accounts.json`
8. Create a new project dir and initialise it as a new npm project.
9. After that do in that project dir: `yarn add @colony/colony-js-client @colony/colony-js-adapter-ethers @colony/colony-js-contract-loader-http ethers`
10. Then paste the following code into an `example.js` file in the project dir: [example.js · GitHub](https://gist.github.com/chmanie/85f1c5cdf5a9f29b47096d05dac32acf)
11. Run `node example.js` in the project dir

**Comment by gichiba** [comment]
Many of these are performed by script in the starter James created, right?

**Comment by gichiba** [comment]
So I've added the changes to the 'get started' doc, but I'm a little unclear on the proper step-by-step for initializing a project with npm (number 8 above)
