### ISSUE TITLE
Better domain handling in createTask sender

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyJS#153]
Currently the `createTask` sender requires a `domainId` to be set. We want to make it a little bit easier for people to use who don't want to concern themselves with domains. So it'd be good to *set the default value of `domainId` to 1* (which is the root domain).

Also, when specifying a `domainId` which doesn't exist, we get a revert error. We should add some async validation so that it checks whether the domain exists before trying to create the task.

TODO:

- [x] Make 1 the default domain
- [x] Adjust the docs (also for the createTask sender) (@gichiba ?)
- [ ] Validate that the domain exists before trying to create a task

**Comment by gichiba** [comment]
I added language into the 'get started' doc for the above, but I think the comments for senders should be changed in the PR that implements the actual code change, right?

**Comment by chmanie** [comment]
> but I think the comments for senders should be changed in the PR that implements the actual code change, right?

Yes, I hope @JamesLefrere is going to take care of this
