### ISSUE TITLE
Fix Dead link in Example.js

### ISSUE THREAD

**Issue by mibzman** [JoinColony/colonyJS#173]
In [this doc](https://joincolony.github.io/colonyjs/docs-get-started/#create-a-new-colony-with-examplejs)
the line 
> Attempting to use these methods without a MultisigOperation will throw an error. You can learn more about Multisignature transactions in colonyJS [here](https://joincolony.github.io/colonyjs/docs-multisignature).

links to this dead link: https://joincolony.github.io/colonyjs/docs-multisignature.

**Comment by mibzman** [comment]
correct link should be https://joincolony.github.io/colonyjs/docs-multisignature-transactions/

**Comment by gichiba** [comment]
Thanks mibzman! Just fixed it (along with some other improvements). Should be redeployed soon!
