### ISSUE TITLE
Find deployed colonies?

### ISSUE THREAD

**Issue by Rkuro** [JoinColony/colonyJS#181]
Hi there!

I'm fairly new at the whole decentralized development operation, I've gone through the getting_started page in the colonyJS documentation and set up my local testing environment via Ganache + Trufflepig and everything seems to be working correctly.  I have a quick question though if someone could help me out:

I know that there is a way to get a particular ColonyClient via the [GetColony](https://joincolony.github.io/colonyjs/api-colonynetworkclient/#getcolonycall-id-) Call.  But is there a way to find all deployed colonies? i.e. query all deployed colonies on the blockchain and show them to a user?  I think this should be done via a [ColonyNetworkClient Caller Method](https://joincolony.github.io/colonyjs/api-colonynetworkclient/#callers), but I don't see an available method there. 

Thanks in advance

**Comment by gichiba** [comment]
Hey @Rkuro, there is currently not a way to do that... But creating an explorer for all colonies is the project of a hackathon participant right now: https://github.com/JoinColony/colonyHackathon/issues/83

**Comment by Rkuro** [comment]
Ah, gotcha, thanks @gichiba

**Comment by KevinLiLu** [comment]
@Rkuro @gichiba They probably did not add a method call to retrieve all colonies as that list would become huge once people start using Colony, and it would be expensive to store in a contract.

Originally we thought of crawling the Colony Network by looking at the outgoing transactions from the Meta Colony that created colonies, but you can actually do it easier by using their ColonyNetworkClient API. 

You would first get the `total-colony-count` via `ColonyNetworkClient.getColonyCount.call()`, and then you can run a loop from index = 1 to `total-colony-count + 1` and call `ColonyNetworkClient.getColony(index)` on each index to retrieve all colonies.
