### ISSUE TITLE
Get Started docs: ganache-cli command needs updated

### ISSUE THREAD

**Issue by cipherpeon** [JoinColony/colonyJS#182]
As with the Note section below the truffle migrate command, there is also an issue if ganache-cli is installed globally. It works if you use

```
./node_modules/.bin/ganache-cli -d --gasLimit 7000000 --acctKeys ganache-accounts.json
```

*edit: typo, thanks @thevaleriemack

**Comment by thevaleriemack** [comment]
Small typo "ganache-cli" but yes thank you!! This worked. How did you know this was the problem..? jw
`./node_modules/.bin/ganache-cli -d --gasLimit 7000000 --acctKeys ganache-accounts.json`

**Comment by cipherpeon** [comment]
No problem! I had a issue when trying to deploy the colony contracts where it was encountering an invalid opcode. The other two commands in the docs which might have caused it were the trufflepig command (which I assumed was correct) and the truffle migrate command which was pinned to the local version, so figured the same needed to apply to the ganache-cli command

**Comment by cipherpeon** [comment]
Yeah that’s the one that worked for me

**Comment by gichiba** [comment]
Awesome; I'll update this in the docs
