### ISSUE TITLE
Docs link broken

### ISSUE THREAD

**Issue by jschiarizzi** [JoinColony/colonyJS#187]
https://docs.colony.io/colonyjs/docs-get-started/#funding-your-colony to authorityClient goes to https://docs.colony.io/docs-authorityclient/ and gives a not found error.

**Comment by gichiba** [comment]
Cool, thanks for catching this! should go to /api-authority client, :)

**Comment by JamesLefrere** [comment]
Thanks for this. Sneakily fixed in #186 👍

**Comment by jschiarizzi** [comment]
You're welcome, nice fix. I surprised it was not pointed out since I'm sure many period are using the getting started guide for the hackathon
