### ISSUE TITLE
Create adapter abstraction for getTransactionReceipt

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyJS#195]
We might need [this logic](https://github.com/JoinColony/colonyJS/commit/02bd502f7e4caec6919138a524ee90cb54b42eda#diff-eda2497d32babcc12083d637fbc0b737R147) more than once (e.g. when deploying contracts). Hence it might make sense to put this into another abstraction which can live in the adapter.

**Comment by JamesLefrere** [comment]
Started this: https://github.com/JoinColony/colonyJS/tree/fix/waitfortransactionreceipt
