### ISSUE TITLE
AuthorityClient always reports `null` for a role using `getUserRole`

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyJS#200]
When running `authorityClient.getUserRole.call({ user: address }), it always reports `null` for the `role`. Sanity checking using `hasUserRole` reveals that the role is indeed different from `null`.

Digging into the code a bit shows that role numbers are `bytes32` that arrive in hex format that isn't parsed in any way here: 

https://github.com/JoinColony/colonyJS/blob/master/packages/colony-js-client/src/paramTypes.js#L19

No role: `0x0000000000000000000000000000000000000000000000000000000000000000`
Admin role: `0x0000000000000000000000000000000000000000000000000000000000000002`

**Comment by ryanchristo** [comment]
@chmanie Looks like there might still be an issue here:

```
// addAdmin

export const addAdmin = async (colonyClient, userAddress) => {

  // add user role admin
  await colonyClient.authority.setUserRole.send({
    user: userAddress,
    role: 'ADMIN',
  })

  // get user role
  const userRole = await colonyClient.authority.getUserRole.call({ user: userAddress })

  console.log('userRole', userRole)

  // check user role admin
  const userRoleAdmin = await colonyClient.authority.hasUserRole.call({ user: userAddress, role: 'ADMIN' })

  console.log('userRoleAdmin', userRoleAdmin)

  // check user role owner
  const userRoleOwner = await colonyClient.authority.hasUserRole.call({ user: userAddress, role: 'OWNER' })

  console.log('userRoleOwner', userRoleOwner)

  // return true
  return true

}
```

```
userRole {role: null}
userRoleAdmin {hasRole: true}
userRoleOwner {hasRole: false}
```

```
// removeAdmin

export const removeAdmin = async (colonyClient, userAddress) => {

  // remove user role admin
  await colonyClient.authority.setUserRole.send({
    user: userAddress,
    role: 'ADMIN',
    enabled: false,
  })

  // get user role
  const userRole = await colonyClient.authority.getUserRole.call({ user: userAddress })

  console.log('userRole', userRole)

  // check user role admin
  const userRoleAdmin = await colonyClient.authority.hasUserRole.call({ user: userAddress, role: 'ADMIN' })

  console.log('userRoleAdmin', userRoleAdmin)

  // check user role owner
  const userRoleOwner = await colonyClient.authority.hasUserRole.call({ user: userAddress, role: 'OWNER' })

  console.log('userRoleOwner', userRoleOwner)

  // return true
  return true

}
```

```
userRole {role: "OWNER"}
userRoleAdmin {hasRole: false}
userRoleOwner {hasRole: false}
```

**Comment by chmanie** [comment]
@ryanchristo Thanks for reporting, I'll reopen this!

**Comment by ryanchristo** [comment]
colony-js-client/src/paramTypes.js

```
...

    if (isHexStrict(value)) {
      converted = hexToNumber(value);

      console.log('convertOutput isHexStrict value', value)
      console.log('convertOutput isHexStrict converted', converted)

...
```

```
convertOutput isHexStrict value
0x0000000000000000000000000000000000000000000000000000000000000002
convertOutput isHexStrict converted 2
```

**Comment by chmanie** [comment]
@ryanchristo this is good input. What do you think of a `getUserRoles` caller function which always returns an array which can be `[]`, `['ADMIN']`, `['OWNER']` and `['ADMIN', 'OWNER']`?

**Comment by ryanchristo** [comment]
@chmanie I like it.

**Comment by ryanchristo** [comment]
@chmanie I'm interested in contributing and wanted to give this one a go. Not sure I am following the design pattern 100% but here is what I came up with: [fix/200-get-user-roles](https://github.com/ryanchristo/colonyJS/tree/fix/200-get-user-roles). Let me know if I should send over a pull request or if I need to make some changes. Also, feel free to reach out on Gitter.

**Comment by chmanie** [comment]
@ryanchristo Thanks so much for your contribution, this is highly appreciated! Feel free to open a PR in which we can progress further. Currently we're having some internal discussions around that topic so that I can't provide a proper review right now, but I'll get back to you ASAP :)

**Comment by ryanchristo** [comment]
Closing in favor of #311
