### ISSUE TITLE
Multisig documentation improvements

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyJS#217]
We have to

- [x] Document that MultiSigs can be sent with just one signature when just one role exists in that task (please make sure in which combinations with `WORKER` and `EVALUATOR` which operations need two signatures (adding a table would be helpful I guess). This was changed in the newest version of the contracts
- [x] Make clear that `refresh` and `sign` are also async operations

**Comment by gichiba** [comment]
testing, testing. *tap* *tap*, is this thing on?
