### ISSUE TITLE
Better explanation and examples for skills and domains

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyJS#219]
In the hackathon people were unsure on how domains and skills related (especially their respective ids). Add a whole lot of examples (and maybe diagrams!) of how to get the root domain, its skill id and how to add skills to that parent domain. Also illustrate local vs. global skills in this context.

Also:

- [X] ~Whats the parentSkillIndex: https://docs.colony.io/colonyjs/api-colonynetworkclient/#getparentskillidcall-skillid-parentskillindex-~
- [X] Explain that `networkClient.getParentSkillId` only works with global skills and why

**Comment by ryanchristo** [comment]
Adding a "Domains and Skills" page to #312 but explaining and using `getParentSkillId` is no longer necessary with #317.
