### ISSUE TITLE
Explain how `payoutsWeCannotMake` works

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyJS#220]
From the gitter:

> How does payoutsWeCannotMake work? It seems the number is always 0 or 1 and 1 even if there are separate addresses for each role within a task and a positive number for each payout assigned to each role within a task.

**Comment by gichiba** [comment]
I'm going to close this issue and move it to a bigger set of improvements that are bound for the colonyNetwork side of things, because it fits better within those docs.
