### ISSUE TITLE
Move documentation generation step to CI

### ISSUE THREAD

**Issue by falafeljan** [JoinColony/colonyJS#237]
Since we're currently discussing whether individually running `docgen` per commit and checking in the generated documentation (https://github.com/JoinColony/colonyJS/pull/236), having the generation of documentation as CI step could benefit in the following ways:
* Documentation won't be contained twice (as comments in the code & as generated Markdown)
* Documentation will get generated automatically, even if edits are made from toolchain-less environments, such as the GitHub editing UI

Documentation could still be generated locally for testing, but generating it with CI would benefit from having it on ignore within the repository.

**Comment by chmanie** [comment]
We _could_ trigger a colony docs gatsby build via the circle API after the PR is merged to master.

**Comment by chmanie** [comment]
> Documentation won't be contained twice (as comments in the code & as generated Markdown)

This is still true as the docs have to live next to the code in the same repository

**Comment by fallafeljan** [comment]
Ah, I was assuming they lived on a `gh-pages` branch!

**Comment by chmanie** [comment]
There seems to be a bit of a confusion around this. So we have:

- The actual code with flow annotations (colonyJS/colony-js-client/src, master branch)
- Markdown templates for ContractClient APIs (colonyJS/colony-js-client/docs, master branch)
- The generated markdown pages for the ContractClient APIs (generated from the two above, colonyJS/docs, master branch)
- The generated HTML pages (colonyDocs, gh-pages branch)
