### ISSUE TITLE
Add specific colonyJS package versions and update colonyNetwork commit

### ISSUE THREAD

**Issue by igorline** [JoinColony/colonyJS#248]
I was trying to run the example described in "Get Started" but the process froze after creating a token and a colony. The problem was fixed after setting `colony-js-adapters-ethers` version to `1.5.3` and reinstalling the dependencies. This should be reflected in the documentation. - @igorline
_____

The original issue has been solved but I'm going to propose we include specific versions for installing the colonyJS packages to prevent this issue in the future. Also, going to note here that the commit for the colonyNetwork needs to be updated. - @ryanchristo 

- [ ] Update colonyNetwork commit
- [ ] Add specific versions to colonyJS packages

**Comment by ryanchristo** [comment]
@igorline Thanks for posting and sorry for the inconvenience! There is a pending pull request (#244) to add specific versions to the example. I will ping the request and we'll get that merged here soon.

**Comment by ryanchristo** [comment]
The original issue has been resolved with update colonyJS packages but I'm going to keep this open as a reminder to set specific versions in the "Getting Started" section of the docs to prevent this issue in the future. Added note to description.
