### ISSUE TITLE
ColonyClient.setTaskRoleUser does not exist

### ISSUE THREAD

**Issue by louismerlin** [JoinColony/colonyJS#263]
`ColonyClient.setTaskRoleUser` is not defined, but it is documented. Has it been replaced ?

We have been trying to `ColonyClient.submitTaskDeliverable`, but have been unable to do so. I think it is because the `WORKER` role is not assigned.

Is there something else I am missing ?

**Comment by louismerlin** [comment]
I digged out `ColonyClient.setTaskWorkerRole` which seems to do the trick ! :mag:

**Comment by ryanchristo** [comment]
@louismerlin Thanks again for pointing this out! There are a few items that need to be fixed in the docs following the latest update to colonyJS. We will be sorting those out this week.
