### ISSUE TITLE
Adjust TokenClient getTokenInfo to support bytes return values

### ISSUE THREAD

**Issue by sprusr** [JoinColony/colonyJS#375]
The `GetTokenInfo` caller currently assumes returned values will be strings, and as a result fails to decode `bytes` values. This is a problem because different token contracts handle this differently - for example `DSToken` returns `bytes32` for `name` and `symbol`. This is a non-standard feature of token contracts and we should support both return types.

See #338 for additional info about the contract changes leading to this.

**Comment by chmanie** [comment]
This is indeed now supported.
