### ISSUE TITLE
Convert Ethers flavoured BigNumbers to bn.js

### ISSUE THREAD

**Issue by sprusr** [JoinColony/colonyJS#381]
Right now we're assuming that any `BigNumber`s Ethers returns are of the `bn.js` flavour. While they are based off this, they have a different set of methods available, which causes confusion - especially since our Flow types say everything is `bn.js` flavour!

A solution is to wrap all BN values we get back from Ethers with something like `new BigNumber(original.toString)`.

**Comment by chmanie** [comment]
Everything is now an ethers bignumber
