### ISSUE TITLE
Support `call`ing methods

### ISSUE THREAD

**Issue by sprusr** [JoinColony/colonyJS#385]
It should be possible to `call` methods (as well as send transactions which execute them). This way users can execute functions on the Ethereum node they're connected to without signing/broadcasting a transaction. This can be used to determine whether a transaction will succeed or not without actually sending it.

The `estimateGas` function already technically does this, but does not provide the full result of the execution.

### Example

```js
// still does this
colonyClient.myMethod.send('an arg')
// -> txResponse

// but also now does this
colonyClient.myMethod.call('an arg')
// -> callResponse (empty for methods which don't return), throws if error
```

**Comment by chmanie** [comment]
Clients are now ethers contracts.
