### ISSUE TITLE
Support more advanced role configuration for DomainAuth

### ISSUE THREAD

**Issue by sprusr** [JoinColony/colonyJS#394]
For each permission configuration for the `DomainAuth` sender, it should be possible to specify cases where:

* All of multiple permissions are required in the same domain in order to call the function
* At least one of multiple permissions are required in order to call the function

This could be done as such:

```js
// one of these
roles: ['this permission', 'or this one']
// all of these
roles: [['this', 'and this']]
```

The following senders should be updated:

* `makePayment`
* `setAdministrationRole`
* `setArchitectureRole`
* `setFundingRole`

**Comment by chmanie** [comment]
This has been rendered irrelevant with v2. If we run into similar problems we should open a new issue.
