### ISSUE TITLE
Use the same ethers version in all subpackages

### ISSUE THREAD

**Issue by bmiller59** [JoinColony/colonyJS#397]
Some packages like `colony-js-adapter-ethers` are using ethers v3 while others like `purser` are using v4. Please use precisely the same version number in all colony packages to avoid multiple versions of ethers being bundled in dapps that use colonyJS.

The same holds true for other dependencies. Thank you.

**Comment by ryanchristo** [comment]
Thanks for opening an issue. This is definitely something we are working on and well aware that the inconsistent versions are not ideal. We have been discussing alternatives to using `ethers` within the colonyJS packages but I think updating `colony-js-adapter-ethers` in the interim is necessary.

**Comment by chmanie** [comment]
This is rendered irrelevant in v2.
