### ISSUE TITLE
Improve Tasks and Payments documentation

### ISSUE THREAD

**Issue by ryanchristo** [JoinColony/colonyJS#417]
## Description

The "Task Lifecycle" documentation currently does not include `setAllTaskPayouts` and needs to clarify the process of setting up a task and the language for what it means to have a task on chain with assigned task roles (multignature is required because reputation is at stake).

There should also be a "Payment Permissions" section in the "Tasks and Payments" page that outlines the permissions for calling payment methods even if there are no payment roles.

https://build.colony.io/t/editing-tasks-clarifying-what-triggers-the-need-for-multi-sig/201

**Comment by chmanie** [comment]
I am closing this for now. We have to revamp that kind of documentation.
