### ISSUE TITLE
Feature request: Implement GraphQL API for Colony

### ISSUE THREAD

**Issue by bmiller59** [JoinColony/colonyJS#438]
## Description

Many people are realizing the benefits of GraphQL generally, and specifically for use with blockchains like Ethereum. (Example: [GraphQL Will Power the Decentralized Web](https://medium.com/graphprotocol/graphql-will-power-the-decentralized-web-d7443a69c69a))

GraphQL is a standardized language for querying disparate resources, allowing for different API details to be hidden through the use of `resolvers`.

To load a meaningful collection of data for a user, for example to load all of the relevant details of a colony to display in a dashboard, may require multiple colonyJS calls to different smart contracts methods. This might require loading various data from the colony contracts, as well as some data from IPFS after those smart contract calls.

Furthermore, GraphQL is useful even when there is centralized server: you can use GraphQL with client side resolvers. [Here is an example of how to do this](https://github.com/hasura/client-side-graphql)

This makes GraphQL appropriate for decentralized platforms like Colony. And allowing users to specify the precise fields they need to load, some of which might be from the Ethereum smart contracts and some from IPFS, using a standardized language like GraphQL, will speed adoption and facilitate development of new dapps.

Please consider offering colonyJS in a GraphQL version, either wrapping or replacing existing API calls in GraphQL resolvers.

**Comment by ryanchristo** [comment]
Thanks for opening an issue @bmiller59! This is something we are looking into and we are excited to explore using GraphQL in colonyJS.

**Comment by gmarko** [comment]
Hi friends, do you say this example?
examples/graphql-wrapper-rest/src/App.js

**Comment by rdig** [comment]
yes, @gmarko that example is showing how to set up a client-only graphQL instance via the apollo client

**Comment by chmanie** [comment]
Closing this for now as it is out of scope for ColonyJS but maybe a good idea for a potential Colony SDK.
