### ISSUE TITLE
Add function to fetch all roles a user has in a domain

### ISSUE THREAD

**Issue by sprusr** [JoinColony/colonyJS#441]
## Description

We've come across the scenario where we want to know _all_ the roles a user has in a domain of a colony, and right now are having to call `hasColonyRole` once for each role (and wrapping all the calls in `Promise.all` for parallelism).

This isn't really ideal, since we're having to write more code than we should need to. A much nicer solution would be to have a function which does this for us in colonyJS! Possibly a `hasColonyRoles` which returns an object like `{ [role]: boolean }`.

**Comment by chmanie** [comment]
We have done that. `getColonyRoles` in the helper functions.
