### ISSUE TITLE
Add fetch support for node to http loader

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyJS#47]
Currently the http contract loader just works in the browser. We need to add a polyfill like https://github.com/matthew-andrews/isomorphic-fetch or https://github.com/bitinn/node-fetch to it when it should be able to be used in node.

Also make sure that this polyfill is only loaded when in a node environment to not blow up the bundle size.

**Comment by JamesLefrere** [comment]
Fixed in #108
