### ISSUE TITLE
Empty browser window instead of Colony!

### ISSUE THREAD

**Issue by vporton** [JoinColony/colonyJS#471]
## Description

When I open https://colony.io/colonystarter/docs-overview

I see empty gray browser window instead of any content.

![Screenshot from 2020-06-27 21-13-43](https://user-images.githubusercontent.com/2900574/85929158-1d686f00-b8bb-11ea-87a3-5a4cf8f240d3.png)

**Comment by chmanie** [comment]
Hey! The docs are here now: https://joincolony.github.io/colonyJS/
