### ISSUE TITLE
Make sure all extension methods have correct overrides

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyJS#495]
## Description

Make sure all the extension methods that we add to the library _(eg: `withProofs` for extensions, or the colony extra methods from `commonExtensions`)_ support and pass along the `overrides` object to the underlying contract call.

Otherwise, it is impossible to manually estimate, and set appropriate `gasPrices`, `gasLimit` values, as well as other values, which come in handy  _(if not downright important sometimes)_:
```js
  gasLimit?: BigNumberish | Promise<BigNumberish>;
  gasPrice?: BigNumberish | Promise<BigNumberish>;
  nonce?: BigNumberish | Promise<BigNumberish>;
  value?: BigNumberish | Promise<BigNumberish>;
  from?: string | Promise<string>;
  chainId?: number | Promise<number>;
```

Here's an example of how one of these extension methods should look like:
```js
async function extraMethod(
  ... // params passed to the underlying contract call
  overrides?: TransactionOverrides,
): Promise<ContractTransaction> {
  await client.contractCall(
   ... // params
    overrides,
  );
```

See this as an example: https://github.com/JoinColony/colonyJS/blob/b210ee702945bd6e2854bdda61cb331a1dae0c7c/src/clients/Extensions/OneTxPayment/1/OneTxPaymentClientAddons.ts#L59-L89

**Comment by chmanie** [comment]
I'm making sure of that in https://github.com/JoinColony/colonyJS/pull/518/commits/42532b64a69318fc008673cd11b47da1355a4f04
