### ISSUE TITLE
Contract Loading

### ISSUE THREAD

**Issue by JamesLefrere** [JoinColony/colonyJS#5]
Create contract loaders (ideally an official Colony Network contract loader and a development loader). The loader will be called from the colony-js client.

As a contract loader, my job is to:

- Provide an ABI manifest and contract address for deployed Colony contracts, given simple parameters (e.g. name of contract and version)

I am "finished" when:

- I provide a simple API to load the API/contract address
- I have an official loader and a dev loader
- I am open-sourced on Github and published on NPM
- I have clear documentation/best practice guide

**Comment by chmanie** [comment]
Are we good here?

**Comment by JamesLefrere** [comment]
Maybe; we could create a new epic for loading versioned contracts (when deployed).

**Comment by chmanie** [comment]
👋 Hey James!
