### ISSUE TITLE
Upgrade lint-staged to version 7.x

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyJS#50]
I tried and it broke things. Apparently you can't run custom scripts anymore but you have to call npm scripts.

Changing it from

`"lint --fix"` to `"yarn run lint --fix"` broke other things, namely the `package.json`s could not be parsed anymore:

```
lerna ERR! /Users/chris/dev/Colony/colony-js/packages/colony-js-contract-loader/package.json
lerna ERR! 2:11  error  Parsing error: Unexpected token, expected ";"
lerna ERR!
lerna ERR! 1 | {
lerna ERR! > 2 |     "name": "@colony/colony-js-contract-loader",
lerna ERR!   |           ^
lerna ERR! 3 |     "version": "1.0.0",
lerna ERR! 4 |     "description": "Contract loader interfaces",
lerna ERR! 5 |     "main": "index.js",
lerna ERR!
lerna ERR! ✖ 1 problem (1 error, 0 warnings)
```

I think that `eslint` tries to lint `.json` files which is quite strange.

**Comment by JamesLefrere** [comment]
`lint-staged` version `7.1.2` now seems to be working AFAICT.
