### ISSUE TITLE
Links to the documentation are dead

### ISSUE THREAD

**Issue by DavidRecheni** [JoinColony/colonyJS#525]
## Description
The links to the docs are dead.
There's on on the README and multiple of them on the CONTRIBUTING : https://joincolony.github.io/colonyJS , https://colony.io/dev/docs/colonyjs
## TODO 
- Update the links or bring those sites back to life

**Comment by chmanie** [comment]
Thank you for opening this and I apologize for the late reply. This issue just slipped through my notifications somehow. I'll change that asap.
