### ISSUE TITLE
Investigate source of unknown event log in colony creation flow

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyJS#537]
## Description

When creating a new colony, the transaction receipt of the `deployToken` method on the network client contains an event log that is not included in the network client's event list, namely: `0xce241d7ca1f669fee44b6fc00b8eba2df3bb514eed0f6f668f8f89096e81ed94`

This causes ethers' `parseLog` method to throw an error, because it cannot match this event's topic hash to any of the events in the network client's event list. 

We're currently catching this in the CDapp and setting the result to null, which imitates how ethers previously behaved (v4) (i.e. it returned null in the event it couldn't match the topic hash to an event in the events list). 

However, it would be better if the event being emitted was parsed with the correct abi.

## To reproduce

- Call the `deployToken` method on the network client
- Then call `client.interface.parseLog` with the log contained in the transaction receipt

Ethers will throw an error. 

**Note:** It is possible that this is occuring for other methods called in the colony creation flow also (and indeed, other methods on the network contracts in general).

**Comment by rdig** [comment]
This is not a bug!

That event was most likely emmited by a different client. Either the colony one, or the token one.

I reiterate, this is not a bug, this is how contracts work.
