### ISSUE TITLE
Web3 adapter

### ISSUE THREAD

**Issue by JamesLefrere** [JoinColony/colonyJS#75]
As a developer using the `colony-js` library, I want the option to use [web3](https://github.com/ethereum/web3.js/), so that I can more easily use it with my `web3`-based project.

Suggestion: aim for the 1.0 version of web3, given its imminent release.

**Comment by ConnorChristie** [comment]
Ethers itself has support for web3 by using the following:
```js
const provider = new providers.Web3Provider(web3.currentProvider);
const signer = provider.getSigner();
```

**Comment by frods** [comment]
stupid question... what modules is providers.Web3Provider from.

**Comment by collinvine** [comment]
@JamesLefrere what's the status of this issue?
